### ISSUE TITLE
Move all yaml and startup scripts out of code or allow overrides

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#46] opened 2018-09-18 17:52 UTC
There are quite a few yaml definitions and startup scripts currently captured in code.  This makes the development/debug cycle very onerous.  It may be fine to keep these in code, but we should allow overrides via clusterctl or other CLI.  The following are scripts and yaml definitions in the code:

1. cluster-apiserver yaml in the main cluster-api repo at cluster-api/pkg/deployer/clusterapiservertemplate.go
2. cni yaml in the vsphere provider repo at cluster-api-provider-vsphere/cloud/vsphere/templates.go
3. master and node startup shell scripts in the provider repo at cluster-api-provider-vsphere/cloud/vsphere/templates.go

As the above described, there are yaml definitions in the code as well as in the input files to clusterctl.  It's a bit of spaghetti and forces a rebuild and docker push to a registry to do a new round of debugging.

**Proposal:**
---
- [ ] separate these non-go code and definitions out of the code into separate files.
- [ ] If we chose to ensure there are defaults, we can package these files into the docker container
- [ ] add command line parameters to the binaries for cluster-apiserver to load its yaml definition from a file.
- [ ] add command line parameters (or add to provider-components.yaml) to clusterctl to load up the cni yaml definition and master/node startup scripts from files.

**Comment by jpweber** [comment] 2019-05-07 02:49
I discovered this today when trying to figure out a way to use something other than weave. I found that was in a go template as well as the kubeadm conf file. As far as I can tell there are not any ways to modify the kubeadm config file to fit user needs other than modifying the `pkg/cloud/vsphere/provisioner/common/templates.go` file.

**Comment by jpweber** [comment] 2019-05-07 02:52
Is this possible a dupe of #19 Or possibly they could be combined.

**Closed** 2019-07-06 04:10 UTC
Labels: kind/feature, lifecycle/rotten
