### ISSUE TITLE
Support for UEFI boot OVAs

### ISSUE THREAD

**Issue by moonek** [kubernetes-sigs/cluster-api-provider-vsphere#954] opened 2020-07-06 10:24 UTC
/kind feature

**Describe the solution you'd like**
I may have gone ahead.
I believe GPU nodes will be supported in cluster api someday.
But I want to manually configure the GPU pass-through to the node created via the current state of CAPV.
GPU pass-through is only supported in UEFI boot mode.
All current CAPV OVAs are considered BIOS boot mode.
Can someone make a UEFI boot mode OVA?

**Comment by yastij** [comment] 2020-07-23 17:49
closing as dupe of #968 which has context and milestone

**Closed by yastij** 2020-07-23 17:49 UTC
Labels: kind/feature
