### ISSUE TITLE
Generating yaml files for self-service steps is wrong using "make prod-yaml" with kustomize master branch

### ISSUE THREAD

**Issue by yuyangbj** [kubernetes-sigs/cluster-api-provider-vsphere#205] opened 2019-02-27 08:26 UTC
The project kustomize has already changed the kustomization.yaml format based on patch below.

https://github.com/kubernetes-sigs/kustomize/pull/700  == all files must be set in sub folder same as kustomization.yaml
https://github.com/kubernetes-sigs/kustomize/pull/752 == secretGenerator has removed commands field

**Comment by sflxn** [comment] 2019-02-28 01:06
The issue is more related to kustomize v2 and not kustomize.  The repo currently does work with kustomize v1.

**Comment by yuyangbj** [comment] 2019-02-28 02:01
@sflxn so should we support kustomize v2 now? Or leave it for v1 and create a new branch for v2?

**Comment by sflxn** [comment] 2019-02-28 18:38
@yuyangbj I believe the other providers are moving to v2 so we might as well move to v2 also.  I assigned myself to this issue, but if you would like to work on this yourself, I can give it to you.  We welcome contributions.

**Comment by sflxn** [comment] 2019-02-28 18:40
Oh, hi Yang.  Are you Yang from the VIC team?  If so, I didn't realize that at first.  In that case, you're welcome to contribute.

**Comment by yuyangbj** [comment] 2019-03-01 03:11
@sflxn yes, it is me :) how are you! I tried the cluster-api on my side, but you know everything I build by myself, so something is broken. I will continue to follow up the PR.

**Closed** 2019-03-04 16:40 UTC
Labels: kind/bug, priority/important-soon
