### ISSUE TITLE
vCloud Director Support

### ISSUE THREAD

**Issue by sachinphogat** [kubernetes-sigs/cluster-api-provider-vsphere#901] opened 2020-04-27 10:06 UTC
/kind feature

Does cluster-api is planning to support vCloud Director  as we are moving all our vsphere infra to vCloud Director for managing VMs and and if yes, any ETA?

**Comment by yastij** [comment] 2020-04-28 18:10
closing as dupe of #902

**Closed by yastij** 2020-04-28 18:10 UTC
Labels: kind/feature
