### ISSUE TITLE
bug: generated kubadm token includes log output

### ISSUE THREAD

**Issue by ntfrnzn** [kubernetes-sigs/cluster-api-provider-vsphere#145] opened 2018-12-04 21:17 UTC
I’m observing a problem with the workers being unable to join a cluster because they haven an invalid token.

In fact, the /tmp/boot.sh script includes
```
TOKEN=I1204 04:46:06.528320      24 version.go:236] remote version is much newer: v1.13.0; falling back to: stable-1.12
ewe864.2i8qadn9rz541i84
```

Log output is prepended to the actual token value

The create-token utility is here:
https://github.com/kubernetes-sigs/cluster-api/blob/e1903be683739379be57f78a4095cd51726495fd/pkg/kubeadm/kubeadm.go#L56

and used:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/fd4d9e1385779fae41393eeae59614ef12490059/pkg/cloud/vsphere/provisioner/govmomi/utils.go#L56

controller log output:
```
I1204 04:46:10.310625       1 controller.go:124] reconciling cluster a3824d30-8bf2-4a34-9645-655273c05fb5 triggers idempotent reconcile.
I1204 04:46:10.311929       1 utils.go:73] Generated kubeadm token I1204 04:46:06.528320      24 version.go:236] remote version is much newer: v1.13.0; falling back to: stable-1.12
ewe864.2i8qadn9rz541i84 from master
```

It's not clear why the log text is being included now.  It would be safer to generate the token in a programmatic way, but if we want to parse stdout, then a regexp can be used
```
KubeadmTokenPattern     = regexp.MustCompile(`(?m)[a-z0-9]{6}\.[a-z0-9]{16}`)
token = KubeadmTokenPattern.FindString(output)
```

**Comment by ntfrnzn** [comment] 2018-12-04 22:04
sample master machine definitions which is at least similar to the one that involved in the problem
```
apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  annotations:
    vm-ip-address: 10.68.192.46
  creationTimestamp: "2018-12-04T21:28:57Z"
  finalizers:
  - machine.cluster.k8s.io
  generateName: ef496a1fcaef-master-1-
  generation: 2
  name: ef496a1fcaef-master-1-6j8wk
spec:
  metadata:
    creationTimestamp: null
  providerConfig:
    value:
      apiVersion: vsphereproviderconfig.sigs.k8s.io/v1alpha1
      kind: VsphereMachineProviderConfig
      machineRef: vm-2248
      machineSpec:
        datacenter: NetApp-HCI-Datacenter
        datastore: NetApp-HCI-Select-Data-04-01
        disks:
        - diskLabel: Hard disk 1
          diskSizeGB: 50
        memoryMB: 4096
        networks:
        - ipConfig:
            networkType: dhcp
          networkName: VM_Network
        numCPUs: 2
        resourcePool: Resources
        template: ubuntu-cloudimg-template
      metadata:
        creationTimestamp: null
  versions:
    controlPlane: 1.11.5
    kubelet: 1.11.5
status:
  providerStatus:
    lastUpdated: 2018-12-04 21:29:11.806427777 +0000 UTC
    taskRef: ""
```

I don't think there's anything unique about the template _ubuntu-cloudimg-template_, pretty vanilla ubuntu iirc.

**Comment by ntfrnzn** [comment] 2018-12-04 22:32
I can confirm that a machine definition like the one above still has the problem, and that the extra text can be filtered out, using a regexp.FindString to get the token:
```
I1204 22:18:19.469013       1 utils.go:62] Got kubeadm token output: I1204 22:18:15.987222      21 version.go:236] remote version is much newer: v1.13.0; falling back to: stable-1.12
i9vkc2.i2ng6jdx5ii68aff
```

**Comment by neolit123** [comment] 2018-12-05 01:33
like already mentioned on slack the instead of doing the kubeadm CLI call to generate a token, either the raw cluster-bootstrap repo k8s.io/cluster-bootstrap should be used directly or this kubeadm backend which is slightly handier:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/bootstraptoken/node/token.go#L37

**Comment by neolit123** [comment] 2018-12-05 01:53
but yes, this is a bit of a problem in 1.12 and we cannot backport a fix for it.
on the other hand the output of the command is not machine readable anyhow.

**Comment by sflxn** [comment] 2018-12-05 23:34
We cannot pull in kubeadm.  It would force us to vendor kubernetes.  We're using cluster-bootstrap to help with this.

**Comment by neolit123** [comment] 2018-12-05 23:41
> We cannot pull in kubeadm. It would force us to vendor kubernetes. We cannot pull in kubeadm. It would force us to vendor kubernetes. We're using cluster-bootstrap to help with this.

ok, that makes perfect sense.

**Comment by sflxn** [comment] 2018-12-05 23:58
@ntfrnzn I wasn't able to reproduce your results; however, code inspection lead to the conclusions we chatted about on slack and that Lubomir mentioned above.  I have a wip to fix this and testing it, but I may have to ask you to see if it fixes your issue.

**Comment by ntfrnzn** [comment] 2018-12-06 00:05
> I have a wip to fix this and testing it, but I may have to ask you to see if it fixes your issue.

@sflxn Sounds great. I'm confident that using _cluster-bootstrap_ is the right approach.  I'm not sure myself what part of my configuration causes the problem, so it's not a very good test framework.

**Comment by sflxn** [comment] 2018-12-06 00:22
@ntfrnzn We have a theory that your bootstrap cluster is running 1.12 and you're creating a target cluster with 1.13, or vice versa.

The token itself is relatively simple to create (random string generator), and that's what cluster-bootstrap does for us.  It took me a little while to see what kubeadm was doing with the token (writing it as a secret into the cluster).

**Comment by ntfrnzn** [comment] 2018-12-06 00:29
@sflxn running 1.12 and creating target clusters of 1.11.5. I'm not sure why kubeadm is concerning itself with 1.13, and debugging it requires reading the /var/log/cloud-init-output.log on the target master, so that's annoying.  I did think that there was something more complex than just the secret creation.

**Comment by neolit123** [comment] 2018-12-06 00:34
kubeadm has this logic of fetching the latest stable version version of upstream.
so a 1.12 client will find the latest stable 1.13 or it could be newer but it will fallback to 1.12 and show the warning.

obviously the warning is intrusive in terms of parsing stdout, so some of these commands should simply not do the remote fetching. i think this is resolved in 1.13, but still an issue in 1.12 that we cannot backport it.

on the other hand stdout should not be parsed, because it's not machine readable, so using the cluster-boostrap utilities is the right thing to do for token generation.

hopefully that explains the situation. :)

**Closed** 2018-12-07 01:57 UTC
Labels: kind/bug

**Comment by sflxn** [comment] 2018-12-07 17:42
@ntfrnzn Would you mind retesting your scenario with the latest update?  The controller from the main repo hadn't been updated updated in awhile (last time I looked).  However, we've built a very recent version that we're using.  You may also use the same.

```
USE_KUBECON=1 make dev-yaml
```

That will generate the yaml files that will utilize the main repo's controller we built and our controller for the provider.

**Comment by ntfrnzn** [comment] 2018-12-10 23:55
@sflxn I built new images for both and it works fine. Thanks!
