### ISSUE TITLE
Sometimes vSphere tasks reports "<machine-name> already exists" on machine creation

### ISSUE THREAD

**Issue by KeithRichardLee** [kubernetes-sigs/cluster-api-provider-vsphere#625] opened 2019-10-14 16:34 UTC
/kind bug

**What steps did you take and what happened:**
Noticed that sometimes, thou not always, on creation of workload cluster machines when it is creating the VMs (from a clone of template) there are two clone tasks for same machine. One task is successful, the other is not and reports reports "<machine-name> already exists" eg"The name 'keithlee-workload-cluster-01-controlplane-0' already exists." 

![Screen Shot 2019-10-14 at 16 40 45](https://user-images.githubusercontent.com/41379304/66766947-39e88680-eea7-11e9-823b-6ce872ca253e.png)

**Environment:**
- capi manifest: v0.5.2-beta.0
- clusterctl: v0.2.5
- kind: v0.5.1
- docker: 19.0.3
- vSphere: 6.7U3
- ova: ubuntu-1804-kube-v1.15.4.ova

**Comment by rikatz** [comment] 2019-10-15 01:36
Did you took a look into this? https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/troubleshooting.md#a-vm-with-the-same-name-already-exists

**Comment by KeithRichardLee** [comment] 2019-10-15 09:53
Yes, already had checked for that. 

@codyde has observed same in his env.

**Comment by codyde** [comment] 2019-10-16 18:58
Confirming - i see this in my environment during creation of an object. What appears to happen is that multiple API calls go out to vCenter (maybe during a reconciliation task?) to create said object, and the object creates as another call hits - thus triggering the message. There's no negative impact to the environment, just a quick error "blip".

**Comment by andrewsykim** [comment] 2019-10-17 18:56
I think this is a race condition in the machine controller as it waits for certain conditions to be satisfied before starting the initial clone. As already mentioned it's pretty harmless but I'll dig into it in-case there's an obvious/quick fix :) 

/assign

**Comment by akutz** [comment] 2019-10-17 18:57
This has been in the code since I started working on the project. I'm sure it's something obvious, but myself and Yuvaraj were never able to isolate the root cause. We've walked the code many times, and we appear to account for all edge cases, but clearly we're not. I'm happy to have you help with this @andrewsykim, thank you!

**Comment by akutz** [comment] 2019-11-04 20:39
#636 would also cover this case.

**Comment by akutz** [comment] 2019-12-16 21:54
/close

Fixed by #655

**Closed by akutz** 2019-12-16 21:54 UTC
Labels: kind/bug
