### ISSUE TITLE
CA certificate is not valid yet when creating clusters

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-vsphere#621] opened 2019-10-12 00:54 UTC
/kind bug

Very similar to #503 

**What steps did you take and what happened:**

- Run the exact steps in the getting started guide.
- Identify VM in vSphere UI, get the IP Address
- `ssh capv@192.168.x.x`
- `sudo su -`
- `less /var/log/cloud-init-output.log`

Contents [other junk removed for brevity]:
```
Cloud-init v. 19.2-36-g059d049c-0ubuntu1~18.04.1 running 'modules:config' at Fri, 11 Oct 2019 18:28:59 +0000. Up 11.61 seconds.
[init] Using Kubernetes version: v1.15.4
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/etc/kubernetes/pki"
error execution phase certs/ca: failure loading ca certificate: failed to load certificate: the certificate is not valid yet
Cloud-init v. 19.2-36-g059d049c-0ubuntu1~18.04.1 running 'modules:final' at Fri, 11 Oct 2019 18:29:01 +0000. Up 13.49 seconds.
2019-10-11 18:29:02,609 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
2019-10-11 18:29:02,612 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2019-10-11 18:29:02,612 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 19.2-36-g059d049c-0ubuntu1~18.04.1 finished at Fri, 11 Oct 2019 18:29:02 +0000. Datasource DataSourceVMwareGuestInfo.  Up 14.66 seconds
```
When manually executing `kubeadm init --config /tmp/kubeadm.yaml` installation continues.

**What did you expect to happen:**

Everything to work.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by voor** [comment] 2019-10-12 01:20
I added the following to my cloud init:
```
  preKubeadmCommands:
  - hostname "{{ ds.meta_data.hostname }}"
  - echo "::1         ipv6-localhost ipv6-loopback" >/etc/hosts
  - echo "127.0.0.1   localhost {{ ds.meta_data.hostname }}" >>/etc/hosts
  - echo "{{ ds.meta_data.hostname }}" >/etc/hostname
  - date -u
  - openssl x509 -in /etc/kubernetes/pki/etcd/ca.crt -noout -text
  - date -u
```

And then got the following output in the log:
```
Cloud-init v. 19.2-36-g059d049c-0ubuntu1~18.04.1 running 'modules:config' at Fri, 11 Oct 2019 22:51:16 +0000. Up 11.89 seconds.
Fri Oct 11 22:51:18 UTC 2019
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 0 (0x0)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = kubernetes
        Validity
            Not Before: Oct 12 01:11:59 2019 GMT
            Not After : Oct  9 01:16:59 2029 GMT
        Subject: CN = kubernetes
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:ec:68:95:6b:af:4c:d5:3c:dc:e6:ae:22:84:2d:
                    10:0b:bf:99:3c:84:e9:f7:7f:47:5e:7c:92:98:0e:
                    c0:da:94:ea:e5:ab:ad:1e:3c:94:7d:a5:19:67:c4:
                    9a:e4:4c:70:2a:a1:db:e4:c3:ec:cc:ba:b4:37:ca:
                    a3:10:eb:4e:96:22:72:ba:22:37:f5:49:17:06:78:
                    39:8d:67:21:18:da:5f:4c:e7:28:c1:8c:57:cd:b7:
                    83:f5:56:66:ad:49:e6:5b:00:81:6b:2d:a9:01:3a:
                    7f:a7:bc:ac:e1:de:af:b5:c6:55:1b:3d:11:4d:90:
                    dd:2a:dd:62:67:9c:de:29:f0:0c:80:99:14:bc:e6:
                    49:72:e9:c3:a4:81:9d:36:88:f3:57:79:0d:93:d0:
                    b9:27:c5:7e:b2:c5:3a:13:0e:39:30:90:3b:1d:63:
                    d4:be:07:3e:56:f1:69:96:45:53:94:1b:fb:c8:61:
                    0d:c1:d0:d1:56:8a:7d:1a:65:62:02:6f:02:d4:9d:
                    4f:eb:62:f6:c8:06:98:85:52:ba:4a:2d:f9:70:08:
                    e4:9a:8a:b7:19:76:82:4c:ce:a3:08:4f:5d:15:ec:
                    93:bc:aa:d5:d8:ab:f2:6e:46:d6:49:83:d1:1b:aa:
                    75:12:36:b0:d8:84:94:db:48:2e:2d:77:37:a5:14:
                    e5:a7
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment, Certificate Sign
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
    Signature Algorithm: sha256WithRSAEncryption
         bd:9b:02:b7:b6:92:3f:a3:7f:27:e0:17:87:f4:87:b5:08:a4:
         78:eb:e0:de:f7:43:c2:49:18:05:17:b1:e4:d4:6e:c8:73:b8:
         af:8d:08:79:c2:3c:0f:c5:98:03:bb:51:2c:e8:00:c4:ed:c9:
         36:e7:dd:f8:d5:ca:54:bd:fd:c0:f5:97:3b:e7:63:65:cc:3c:
         cc:cb:cb:bc:4c:1c:a8:77:60:42:9a:57:52:b4:5e:d6:e3:6b:
         45:73:91:f2:4c:70:9f:0d:91:7c:20:19:42:e8:9a:1e:a3:cb:
         a5:33:86:56:83:7d:b8:8b:63:ed:94:18:48:e4:35:db:1e:6b:
         0d:d0:1a:05:fd:c4:e8:df:62:72:46:6c:6e:c0:b8:5e:a0:e2:
         ae:d5:c7:1c:a6:7f:25:3e:59:1f:1b:6e:cb:ce:1e:d3:57:28:
         8c:cf:51:92:7b:98:25:8b:87:4e:23:6a:2b:1b:33:bf:16:b8:
         fd:2c:66:83:e0:9f:6d:57:97:18:17:d5:83:a5:3c:24:a4:65:
         ed:eb:da:07:f0:d8:52:c2:b0:25:a1:01:4d:ed:62:f4:b9:d3:
         fe:02:7e:2b:af:ac:98:e1:27:f4:e0:2f:ae:54:9e:08:a4:42:
         d2:de:98:47:10:d7:1c:6c:2c:99:a3:c0:17:d5:ab:6c:61:a2:
         f5:aa:46:25
Fri Oct 11 22:51:18 UTC 2019
```

**Comment by voor** [comment] 2019-10-23 20:07
I am currently getting around this issue by explicitly specifying a ntp server in `KubeadmConfig` and `KubeadmConfigTemplate`:

```
  ntp:
    enabled: true
    servers:
      - INTERNAL_NTP
```

**Comment by voor** [comment] 2019-10-24 17:41
The above fix does *not* work for Photon OS, not sure why not though.

**Comment by akutz** [comment] 2019-11-04 20:38
Hi @voor,

As @andrewsykim already mentioned, I think this may be a duplicate of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/645. Can you please take a look at that issue or ping @kacole2 and see his solution works for you?

**Comment by voor** [comment] 2019-11-04 20:49
Definitely didn't have NTP service running on the host (whoops), will need to retest to see if this resolves the issue.

**Comment by voor** [comment] 2019-11-04 20:55
I would like to point out that if this is the *second* issue opening up on this topic, I would thing it might warrant some more detailed error logging back to where it would get more visibility.  In that case, I wouldn't want to close this issue, but instead make it a feature request that when NTP isn't working properly it's very obvious.

**Comment by akutz** [comment] 2019-11-04 21:01
It's difficult to make anything obvious that occurs inside the guest. An admission webhook that queries the state of the ESX hosts' NTP service is a possibility though.

**Comment by voor** [comment] 2019-11-04 21:14
That's a really hard one, too, since you're effectively going through vCenter and wouldn't really know hwich ESX host you're hitting. :thinking:

**Comment by akutz** [comment] 2019-11-04 21:40
Should we consider adding a requirement to CAPV that ESX hosts be configured correctly with NTP?

**Comment by akutz** [comment] 2019-11-04 21:43
@sidharthsurana recommends documentation that says:

* The time must be sync'd via VM tools and the ESX hosts

or

* The guests' NTP settings are configured via the `KubeadmConfig` resource

**Closed** 2019-11-05 17:04 UTC
Labels: kind/bug
