### ISSUE TITLE
Bug: VM orphan left running after machine CR is deleted

### ISSUE THREAD

**Issue by ntfrnzn** [kubernetes-sigs/cluster-api-provider-vsphere#235] opened 2019-03-25 20:37 UTC
While running some manual tests, I twice observed a VM that continued running long after the machine CR had been deleted.  The general scenario involved a machineset that was scaled up and down in quick sequence by independent processes. It appears that a machine was deleted by a controller without successfully invoking the vsphere provider code.

The cluster-api and cluster-api-provider-vsphere codebases were current to 2019/03/22 (with minor changes not related to vsphere).

If I have time to try to reproduce it (or come across it again) I will add better details.

**Comment by sidharthsurana** [comment] 2019-03-25 20:50
@ntfrnzn I know the issue. This is because the delete operation currently, does not take in account the time when the clone operation has started but not completed. (This behavior was kind of on my personal list to operations to improve, but just didn't got time to implement this)

The issue is that the current delete implementation only covers the simple case of delete the VM as tracked by the Machine object. Ideally, it needs to also take in account and pending vm clone task operation that might be going on. It's a relatively simple fix, in case you can contribute a fix for this that would be great.

Below is what is needed to happen in the delete method (current implementation only covers case 1 below):
1. Check VM ref exists-> delete the VM (done)
2) If not case 1, then check for the taskRef in the ProviderStatus, 
2a) if the taskRef exists and is running, trigger the CancelTask operation
2b) if the taskRef exists and got completed, look at the Task Result for the VM moid, and then trigger a delete on that VM (same as case 1 ^^) 
3) neither VMRef exists not the TaskRef exists then its a noOP and simply let the CR deleted.

**Closed** 2019-06-24 21:16 UTC
Labels: kind/bug, priority/important-soon
